INSERT INTO `quotes` (quote) VALUES
    ('Obstacles are the cost of greatness. Robin Sharma' ),
    ('The question isnt who is doing to let me its who is going to stop me. Ayn Rand '),
    ('I wasn\'t there to compete. I was there to win. Arnold Schwarzenegger '),
    ('All the power is within you. You can do anything. Swami Vivekananda '),
    ('The place between your comfort zone and your dream is where life takes place. Helen Keller '),
    ('Stop whining start grinding. Eric Thomas '),
    ('To be a star you must shine your own light follow your own path and don\'t worry about darkness for that is when the stars shine brightest. Napoleon Hill '),
    ('Never bend your head. Hold it high. Look the world straight in the eye. Helen Keller '),
    ('What you want exists. Don\'t settle until you get it. Jay Shetty '),
    ('Work hard be kind and amazing things will happen. Conan O\'Brien '),
    ('How bad do you want it? Gary Vaynerchuk'),
    ('I am not afraid  I was born to do this. Joan of Arc'),
    ('If you fell down yesterday stand up today. H.G. Wells'),
    ('The only person you are destined to become is the person you decide to be. Ralph Waldo Emerson'),
    ('Blood sweat and respect. First two you give. Last one you earn. Dwayne Johnson (The Rock)'),
    ('Conformity gets you nowhere. Neil Strauss '),
    ('Be so good they can\'t ignore you. Steve Martin'),
    ('Show the world how much you\'ll fight for the winners circle. Pat Riley'),
    ('If you don\'t design your own life plan chances are you\'ll fall into someone else\'s plan and guess what they have planned for you? Not much. Jim Rohn'),
    ('Action is the real measure of intelligence. Napoleon Hill '),
    ('Everything you\'ve ever wanted is on the other side of fear. George Addair '),
    ('It\'s your place in the world: it\'s your life. Go on and do all you can with it and make it the life you want to live. Mae Jemison'),
    ('Those who truly want something will keep trying until they die. Maxime Lagacce'),
    ('Learn to be comfortable in the uncomfortable. Learn to be peaceful not bored. Learn to be inspired not scared. Maxime Lagacce'),
    ('Make each day your masterpiece. John Wooden'),
    ('Don\'t count the days make the days count. Muhammad Ali'),
    ('Everything you can imagine is real. Pablo Picasso'),
    ('Develop success from failures. Discouragement and failure are two of the surest stepping stones to success. Dale Carnegie'),
    ('It\'s not what you say out of your mouth that determines your life it\'s what you whisper to yourself that has the most power. Robert T. Kiyosaki'),
    ('Do what you have to do until you can do what you want to do. Oprah Winfrey'),
    ('Fall seven times stand up eight. Japanese proverb'),
    ('You\'re probably on the right track if you feel like a sidewalk worm during a rainstorm. Larry Page (Google)'),
    ('Always ask yourself if what you\'re doing today is getting you closer to where you want to be tomorrow. Paulo Coelho'),
    ('Do not wait to strike till the iron is hot. Make it hot by striking. William Butler Yeats'),
    ('I can\'t believe that God put us on this earth to be ordinary. Lou Holtz'),
    ('I want the world to be better because I was here. Will Smith '),
    ('The habit of persistence is the habit of victory. Herbert Kaufman'),
    ('Don\'t be afraid to give up the good to go for the great. John D. Rockefeller'),
    ('Do your duty and a little more and the future will take care of itself. Andrew Carnegie'),
    ('When you do the common things in life in an uncommon way you will command the attention of the world. George Washington Carver'),
    ('No simply means begin again at one level higher. Peter Diamandis'),
    ('To seek greatness is the only righteous vengeance. Criss Jami'),
    ('It\'s hard to beat a person who never gives up. Babe Ruth '),
    ('Every strike brings me closer to the next home run. Babe Ruth'),
    ('Do the best you can until you know better. Then when you know better do better. Maya Angelou'),
    ('If you can dream it you can do it. Walt Disney'),
    ('The way to get started is to quit talking and begin doing. Walt Disney'),
    ('Only those who dare to fail greatly can ever achieve greatly. Robert F. Kennedy'),
    ('If one advances confidently in the direction of his dreams and endeavors to live the life which he has imagined he will meet with a success unexpected in common hours. Henry David Thoreau'),
    ('Win from within. Usain Bolt '),
    ('Believe you can and you\'re halfway there. Theodore Roosevelt'),
    ('Never never never give up. Winston Churchill'),
    ('If you\'re going through hell keep going. Winston Churchill'),
    ('Success is walking from failure to failure with no loss of enthusiasm. Winston Churchill'),
    ('Strength does not come from physical capacity. It comes from an indomitable will. Mahatma Gandhi'),
    ('Diligence is the mother of good luck. Benjamin Franklin'),
    ('Energy and persistence conquer all things. Benjamin Franklin'),
    ('Don\'t stop when you\'re tired: stop when you\'re done. Marilyn Monroe'),
    ('The only place where success comes before work is in the dictionary. Vince Lombardi'),
    ('The secret of getting ahead is getting started. Mark Twain (More info on the source here)'),
    ('Unless someone like you cares a whole awful lot nothing is going to get better. It\'s not. Dr. Seuss'),
    ('Whatever the mind of man can conceive and believe it can achieve. Napoleon Hill'),
    ('Whether you think you can or you think you can\'t you\'re right. Henry Ford'),
    ('Your time is limited so don\'t waste it living someone else\'s life. Don\'t be trapped by dogma. Steve Jobs'),
    ('It is not the strength of the body that counts but the strength of the spirit. J.R.R. Tolkien'),
    ('Concentrate all your thoughts upon the work at hand. The sun\'s rays do not burn until brought to a focus. Alexander Graham Bell'),
    ('I have been impressed with the urgency of doing. Knowing is not enough: we must apply. Being willing is not enough: we must do. Leonardo da Vinci'),
    ('If you can\'t fly then run if you can\'t run then walk if you can\'t walk then crawl but whatever you do you have to keep moving forward. Martin Luther King Jr'),
    ('Life shrinks or expands in proportion to one\'s courage. Anais Nin'),
    ('I was taught that the way of progress was neither swift nor easy. Marie Curie'),
    ('There is always room at the top. Daniel Webster '),
    ('Action is character. F. Scott Fitzgerald'),
    ('Leap and the net will appear. John Burroughs'),
    ('Be your own hero. Maxime Lagacce'),
    ('I prefer to die trying. Maxime Lagacce'),
    ('Wake up determined. Go to bed satisfied. Dwayne Johnson (The Rock)'),
    ('I like getting to that point where it\'s hard and then pushing harder. Zach Miller'),
    ('Light tomorrow with today. Elizabeth Barrett Browning'),
    ('Show them what crazy dreams can do. Nike'),
    ('We must act. Marie Curie'),
    ('Remember why you started. Erin Janus'),
    ('Success is my only option failure\'s not. Eminem'),
    ('I am not talented. I am obsessed. Conor McGregor'),
    ('You could be anyone if you put the time. Conor McGregor'),
    ('Nothing is given. Everything is earned. LeBron James'),
    ('If you can\'t stop thinking about it don\'t stop working for it. Unknown'),
    ('I didn\'t come this far to only go this far. Unknown'),
    ('The moment you want to quit is the moment you need to keep pushing. Unknown'),
    ('One day or day one. It\'s your choice. Unknown '),
    ('Don\'t wait for opportunity. Create it. Unknown'),
    ('You are your only limit. Unknown'),
    ('Prove them wrong. Unknown'),
    ('I can and I will. Unknown'),
    ('Don\'t call it a dream call it a plan. Unknown'),
    ('What you allow is what will continue. Unknown'),
    ('Don\'t stop until you\'re proud. Unknown '),
    ('Don\'t look back you\'re not going that way. Unknown'),
    ('You are capable of amazing things. Unknown'),
    ('Better an oops than a what if. Unknown'),
    ('Storms make trees take deeper roots. Unknown'),
    ('Don\'t wish for it. Work for it. Unknown'),
    ('Will it be easy? No. Will it be worth it? Absolutely. Unknown'),
    ('Strive for progress not perfection. Unknown'),
    ('Feel the fear. Do it anyway! Jillian Michaels'),
    ('Don\'t wait. The time will never be just right. Napoleon Hill'),
    ('Half-heartedness never won a battle. William McKinley'),
    ('Good is the enemy of great. Jony Ive (Apple)'),
    ('Quality is not an act it is a habit. Aristotle'),
    ('Aim for the highest. Andrew Carnegie'),
    ('Do your thing and don\'t care if they like it. Tina Fey '),
    ('What you do today can improve all your tomorrows. Ralph Marston'),
    ('And you ask What if I fall?. Oh but my darling â€œWhat if you fly?. Erin Hanson'),
    ('Nothing happens to anybody which he is not fitted by nature to bear. Marcus Aurelius'),
    ('You don\'t have to be great to start but you have to start to be great. Zig Ziglar'),
    ('What\'s the tiniest step you can take? Do that first. Maxime Lagacce'),
    ('Character cannot be developed in ease and quiet. Only through experiences of trial and suffering can the soul be strengthened vision cleared ambition inspired and success achieved. Helen Keller'),
    ('Don\'t bend don\'t water it down don\'t try to make it logical: don\'t edit your own soul according to the fashion. Rather follow your most intense obsessions mercilessly. Franz Kafka'),
    ('Most of the things worth doing in the world had been declared impossible before they were done. Louis D. Brandeis'),
    ('Knowing what you want and going after it every day is one of the most beautiful things anyone can have in life. Tom Bilyeu'),
    ('Everything will happen for you all of a sudden and you will be thankful you didn\'t give up. Blessings are coming. Believe that. Jay Shetty'),
    ('Become the best in the world at what you do. Keep redefining what you do until this is true. Naval Ravikant'),
    ('I am not what happened to me. I am what I choose to become. Unknown'),
    ('Strength grows in the moments you can\'t go on but you keep going anyway. Unknown'),
    ('I realized that I don\'t have to be perfect. All I have to do is show up and enjoy the messy imperfect and beautiful journey of life. Unknown'),
    ('I\'m not here to be average. I\'m here to be awesome. Unknown'),
    ('Your potential is endless. Go do what you were created to do. Unknown'),
    ('How many success stories do you need to hear before you make your own? Unknown'),
    ('Start where you are. Use what you have. Do what you can. Arthur Ashe '),
    ('The size of your success is measured by the strength of your desire the size of your dream and how you handle disappointment along the way. Robert Kiyosaki'),
    ('It\'s our own ability to have an idea and go after the idea and make it happen. That\'s what at the end of the day defines us. Satya Nadella (Microsoft)'),
    ('I want to be looked back on as being very innovative very trusted and ethical and ultimately making a big difference in the world. Sergey Brin (Google)'),
    ('Having faith beliefs and convictions is a great thing but your life is measured by the actions you take based upon them. Nick Vujicic'),
    ('Think of yourself as on the threshold of unparalleled success. A whole clear glorious life lies before you. Achieve! Achieve! Andrew Carnegie'),
    ('Success is to be measured not so much by the position that one has reached in life as by the obstacles which he has overcome. Booker T. Washington'),
    ('If you want to lift yourself up lift up someone else. Booker T. Washington'),
    ('A positive mind finds a way it can be done: A negative mind looks for all the ways it can\'t be done. Napoleon Hill'),
    ('When your desires are strong enough you will appear to possess superhuman powers to achieve. Napoleon Hill'),
    ('We\'re not playing solitaire out here. Bill Parcells '),
    ('The ultimate inspiration is the deadline. Nolan Bushnell'),
    ('Expect problems and eat them for breakfast. Alfred A. Montapert'),
    ('Don\'t worry about looking good worry about achieving your goals. Ray Dalio'),
    ('You can\'t be that kid standing at the top of the waterslide overthinking it. You have to go down the chute. Tina Fey'),
    ('Doing nothing is very hard to do  you never know when you\'re finished. Leslie Nielsen'),
    ('There are seven days in a week and someday isn\'t one of them. Unknown'),
    ('Only dead fish go with the flow. Unknown'),
    ('Big shots are only little shots who keep shooting. Christopher Morley'),
    ('You miss 100% of the shots you don\'t take. Wayne Gretzky '),
    ('Dream as if you\'ll live forever. Live as if you\'ll die today. James Dean'),
    ('Perfection is not attainable but if we chase perfection we can catch excellence. Vince Lombardi'),
    ('Aim for the moon. If you miss you may hit a star. W. Clement Stone'),
    ('A quitter never wins and a winner never quits. Napoleon Hill'),
    ('Of course motivation is not permanent. But then neither is bathing: but it is something you should do on a regular basis. Zig Ziglar'),
    ('If life gives you lemons make lemonade. Unknown'),
    ('Live every day like it\'s your last. Unknown'),
    ('Be like a postage stamp stick to one thing until you get there. Unknown'),
    ('You can\'t make a rainbow without a little rain. Unknown'),
    ('Don\'t watch the clock: do what it does. Keep going. Sam Levenson'),
    ('Either you run the day or the day runs you. Jim Rohn'),
    ('Sweat is the cologne of accomplishment. Heywood Hale Broun'),
    ('Whenever I feel the need to exercise I lie down until it goes away. Paul Terry '),
    ('Even if you fall on your face you\'re still moving forward. Victor Kiam'),
    ('If your only goal is to become rich you will never achieve it. John D. Rockefeller'),
    ('I think everybody should get rich and famous and do everything they ever dreamed of so they can see that it\'s not the answer. Jim Carrey'),
    ('It\'s never too late to go back to bed. Unknown'),
    ('It is what it is. And it\'s not good. Unknown'),
    ('I do marathons on Netflix. Unknown'),
    ('Work hard. Complain harder. Unknown'),
    ('Procrastinate now. Don\'t put it off. Ellen DeGeneres'),
    ('There are four basic human needs: food sleep sex and revenge. Banksy '),
    ('What I\'m looking for is not out there it is in me. Helen Keller'),
    ('If you are not doing what you love you are wasting your time. Billy Joel'),
    ('It is never too late to be what you might have been. George Eliot'),
    ('Hardships often prepare ordinary people for an extraordinary destiny. C.S. Lewis '),
    ('Remember that not getting what you want is sometimes a wonderful stroke of luck. Dalai Lama'),
    ('Too many of us are not living our dreams because we are living our fears. Les Brown'),
    ('We either make ourselves miserable or we make ourselves strong. The amount of work is the same. Carlos Castaneda'),
    ('I have had all of the disadvantages required for success. Larry Ellison (Oracle)'),
    ('Life has a way of testing a person\'s will either by having nothing happen at all or by having everything happen at once. Paulo Coelho'),
    ('A wise man can always be found alone. A weak man can always be found in crowd. Unknown'),
    ('To dare is to lose one\'s footing momentarily. Not to dare is to lose oneself. Soren Kierkegaard'),
    ('Fear defeats more people than any other one thing in the world. Ralph Waldo Emerson'),
    ('What are the most powerful words in the universe? The ones you use to talk to yourself. Karen Salmansohn'),
    ('My mama always used to tell me:\'If you can\'t find somethin\' to live for you best find somethin\' to die for. Tupac'),
    ('Motivation comes from meaning. Everything comes from meaning. Jay Shetty'),
    ('If you do not conquer self you will be conquered by self. Napoleon Hill'),
    ('You have to be at your strongest when you\'re feeling at your weakest. Unknown'),
    ('It doesn\'t get easier. You get stronger. Unknown'),
    ('There is no class so pitiably wretched as that which possesses money and nothing else. Andrew Carnegie'),
    ('A man as a general rule owes very little to what he is born with a man is what he makes of himself. Alexander Graham Bell'),
    ('Sentiment without action is the ruin of the soul. Edward Abbey'),
    ('Most people fail in life because they major in minor things. Tony Robbins '),
    ('It is not the path which is the difficulty: rather it is the difficulty which is the path. Soren Kierkegaard'),
    ('A hero is one who knows how to hang on for one minute longer. Norwegian proverb'),
    ('Finishing something will give you satisfaction. Finishing something important to you will give you meaning. A meaningful life is a good life. Maxime Lagacce'),
    ('The most important thing is to continue. Forget about others forget about the scoreboard forget about your failures. Just keep pushing. Maxime Lagacce'),
    ('To avoid criticism say nothing do nothing be nothing. Elbert Hubbard'),
    ('You don\'t discover your place in the world. You carve it out. Thibaut'),
    ('Winners focus on winning. Losers focus on winners. Eric Thomas'),
    ('Winners never quit and quitters never win. Vince Lombardi'),
    ('Failure will never overtake me if my determination to succeed is strong enough. Og Mandino'),
    ('What comes easy won\'t last. What lasts won\'t come easy. Unknown'),
    ('You\'ve got to get up every morning with determination if you\'re going to go to bed with satisfaction. George Lorimer'),
    ('Go as far as you can see: when you get there you\'ll be able to see further. Thomas Carlyle'),
    ('Don\'t do what you can do try what you can\'t do. William Faulkner '),
    ('Someone once told me growth and comfort do not coexist. And I think it\'s a really good thing to remember. Ginni Rometty (IBM)'),
    ('Embrace bad news to learn where you need the most improvement. Bill Gates'),
    ('A happy life consists not in the absence but in the mastery of hardships. Helen Keller'),
    ('It is always your next move. Napoleon Hill'),
    ('Let your workings remain a mystery. Just show people the results. Lao Tzu '),
    ('The man who has confidence in himself gains the confidence of others. Hasidic proverb'),
    ('The man who does more than he is paid for will soon be paid for more than he does. Napoleon Hill'),
    ('Genius begins great works: labor alone finishes them. Joseph Joubert'),
    ('One of the greatest satisfaction in life is creating something you truly believe in. Maxime Lagacce'),
    ('Do what you love and don\'t stop until you get what you love. Work as hard as you can imagine immensities. Debbie Millman'),
    ('Done is better than perfect. Sheryl Sandberg (Facebook)'),
    ('Even if you on the right track you\'ll get run over if you just sit there. Will Rogers'),
    ('True happiness comes from the joy of deeds well done the zest of creating things new. Antoine de Saint-Exupery'),
    ('A company shouldn\'t get addicted to being shiny because shiny doesn\'t last. Jeff Bezos (Amazon)'),
    ('Work gives you meaning and purpose and life is empty without it. Stephen Hawking'),
    ('When something is important enough you do it even if the odds are not in your favor. Elon Musk (Tesla)'),
    ('Failure is an option here. If things are not failing you are not innovating enough. Elon Musk (Tesla)'),
    ('You get the best out of others when you give the best of yourself. Harvey Firestone'),
    ('Leadership is an action not a position. Donal McGannon'),
    ('Be so ridiculously great at what you do that the world cannot help but give you an audience. Joubert Botha'),
    ('Our work is the presentation of our capabilities. Edward Gibbon'),
    ('Your income right now is a result of your standards it is not the industry it is not the economy. Tony Robbins'),
    ('Leaders spend 5% of their time on the problem and 95% of their time on the solution. Get over it and crush it! Tony Robbins'),
    ('We are judged by what we finish not by what we start. Unknown'),
    ('The ability to concentrate and to use time well is everything. Lee Iacocca (Ford) '),
    ('Management is nothing more than motivating other people. Lee Iacocca'),
    ('The speed of the boss is the speed of the team. Lee Iacocca'),
    ('I believe in the dignity of labor whether with head or hand: that the world owes no man a living but that it owes every man an opportunity to make a living. John D. Rockefeller'),
    ('I believe you have to be willing to be misunderstood if you\'re going to innovate. Jeff Bezos (Amazon)'),
    ('If you only do thing where you know the answer in advance your company goes away. Jeff Bezos (Amazon)'),
    ('We are limited not by our abilities but by our vision. Kahlil Gibran'),
    ('No man can become rich without himself enriching others. Andrew Carnegie'),
    ('Alone we can do so little: together we can do so much. Helen Keller'),
    ('The greater the difficulty the greater the glory. Cicero '),
    ('Failure is the condiment that gives success its flavor. Truman Capote'),
    ('Adversity causes some men to break: others to break records. William Arthur Ward'),
    ('Although the world is full of suffering it is full also of the overcoming of it. Helen Keller'),
    ('The clearer you are about the impact you want to have in the world the less intimidating obstacles will look like. Maxime Lagacce'),
    ('The most important thing in life is to stop saying\'I wish\' and start saying\'I will\'. Consider nothing impossible then treat possibilities as probabilities. Charles Dickens'),
    ('Wear your failure as a badge of honor. Sundar Pichai (Google)'),
    ('It\'s fine to celebrate success but it is more important to heed the lessons of failure. Bill Gates (Microsoft)'),
    ('All that was great in the past was ridiculed condemned combated suppressed â€ only to emerge all the more powerfully all the more triumphantly from the struggle. Nikola Tesla'),
    ('The challenges in our lives are there to strengthen our convictions. They are not there to run us over. Nick Vujicic'),
    ('Character cannot be developed in ease and quiet. Only through experience of trial and suffering can the soul be strengthened ambition inspired and success achieved. Nick Vujicic'),
    ('Sometimes you have to get knocked down lower than you have ever been to stand back up taller than you ever were. Jim Kwik'),
    ('All my problems bow before my stubbornness. Amit Kalantri');