INSERT INTO quotes (quote) VALUES
    ('If you get tired learn to rest not to quit. Banksy'),
    ('Falling down is an accident. Staying down is a choice. Unknown'),
    ('No matter how much it hurts now someday you will look back and realize your struggles changed your life for the better. Unknown'),
    ('Don\'t you dare give up on this life. Not tonight. Not tomorrow. Not ever. Unknown'),
    ('Sometimes you have to get knocked down lower than you have ever been to stand back up taller than you ever were. Unknown'),
    ('I do not think that there is any other quality so essential to success of any kind as the quality of perseverance. It overcomes almost everything even nature. John D. Rockefeller'),
    ('I always tried to turn every disaster into an opportunity. John D. Rockefeller '),
    ('Let me tell you the secret that has led me to my goal. My strength lies solely in my tenacity. Louis Pasteur'),
    ('Most great people have achieved their greatest success just one step beyond their greatest failure. Napoleon Hill'),
    ('First principle: never to let one\'s self be beaten down by persons or by events. Marie Curie'),
    ('When it\'s darkest men see the stars. Ralph Waldo Emerson'),
    ('Some people dream of success while others wake up and work hard at it. Napoleon Hill '),
    ('I truly believe that in order to truly be great at something you have to give into a certain amount of madness. Joe Rogan'),
    ('Confidence comes from experience. Experiences comes from trying and failing and trying again this time better. Maxime Lagacce'),
    ('The time that leads to mastery is dependent on the intensity of our focus. Robert Greene'),
    ('The less you fear the more power you will have and the more fully you will live. Robert Greene'),
    ('If you give up on your dreams what\'s left? Jim Carrey'),
    ('Success is a state of mind. If you want success start thinking of yourself as a success. Joyce Brothers'),
    ('It takes courage to grow up and become who you really are. E.E. Cummings'),
    ('Success only comes to those who dare to attempt. Mallika Tripathi'),
    ('One important key to success is self-confidence. An important key to self-confidence is preparation. Arthur Ashe'),
    ('I was always looking outside myself for strength and confidence but it comes from within. It was there all the time. Anna Freud'),
    ('Doubt kills more dreams than failure ever will. Suzy Kassem'),
    ('Anything that gets your blood racing is probably worth doing. Hunter S. Thompson'),
    ('Victory is always possible for the person who refuses to stop fighting. Napoleon Hill'),
    ('You\'ll never change your life until you change something you do daily. The secret of your success is found in your daily routine. John C. Maxwell'),
    ('The only thing standing between you and your goal is the bullshit story you keep telling yourself as to why you can\'t achieve it. Jordan Belfort (The Wolf Of Wall-Street)'),
    ('To be successful your focus has to be so intense that others think you\'re crazy. Unknown'),
    ('You did not wake up today to be mediocre. Unknown'),
    ('Don\'t tell people your dreams. Show them. Unknown'),
    ('Your imagination is your preview of life\'s coming attractions. Albert Einstein '),
    ('Rarely are opportunities presented to you in a perfect way. In a nice little box with a yellow bow on top. Susan Wojcicki (YouTube)'),
    ('Obstacles are those frightful things you see when you take your eyes off your goal. Henry Ford'),
    ('If you want to succeed you should strike out on new paths rather than travel the worn paths of accepted success. John D. Rockefeller'),
    ('The men who have succeeded are men who have chosen one line and stuck to it. Andrew Carnegie'),
    ('The most successful men in the end are those whose success is the result of steady accretion. Alexander Graham Bell'),
    ('Any idea plan or purpose may be placed in the mind through repetition of thought. Napoleon Hill'),
    ('Finding an opportunity is a matter of believing it\'s there. Barbara Corcoran'),
    ('Setting goals is the first step in turning the invisible into the visible. Tony Robbins'),
    ('The path to success is to take massive determined action. Tony Robbins'),
    ('If you don\'t risk anything you risk even more. Erica Jong '),
    ('Opportunities don\'t happen you create them. Chris Grosser'),
    ('If you can\'t change a situation change your mind. Unknown'),
    ('With the new day comes new strength and new thoughts. Eleanor Roosevelt'),
    ('When we are no longer able to change a situation we are challenged to change ourselves. Viktor E. Frankl'),
    ('What you\'re afraid is not the sea but to lose sight of the shore. Remember: the promised land is on the other side. Maxime Lagacce'),
    ('No matter how hard the past is you can always begin again. Jack Kornfield'),
    ('If you dare nothing then when the day is over nothing is all you will have gained. Neil Gaiman'),
    ('Very often a change of self is needed more than a change of scene. Arthur Christopher Benson'),
    ('If you want a future that makes you happy if you want a world that you\'re excited about get your ass out there and earn it. Tom Bilyeu'),
    ('We must be willing to let go of the life we planned so as to have the life that is waiting for us. Joseph Campbell'),
    ('The biggest risk is not taking any risk. In a world that\'s changing really quickly the only strategy that is guaranteed to fail is not taking risks. Mark Zuckerberg (Facebook)'),
    ('Fear is the biggest disability of all. And will paralyze you more than being in a wheelchair. Nick Vujicic'),
    ('The only way of discovering the limits of the possible is to venture a little way past them into the impossible. Arthur C. Clarke'),
    ('If you do what you\'ve always done you\'ll get what you\'ve always gotten. Tony Robbins '),
    ('We can change our lives. We can do have and be exactly what we wish. Tony Robbins'),
    ('The starting point of all achievement is desire. Keep this constantly in mind. Weak desires bring weak results just as a small fire makes a small amount of heat. Napoleon Hill'),
    ('All achievements all earned riches have their beginning in an idea. Napoleon Hill'),
    ('Be willing to sacrifice what you think you have today for the life that you want tomorrow. Neil Strauss'),
    ('Some injuries heal more quickly if you keep moving. Nick Vujicic'),
    ('What\'s dangerous is not to evolve. Jeff Bezos (Amazon)'),
    ('Either I will find a way or I will make one. Philip Sidney'),
    ('The only way to shut everybody up is to win. Terry Bradshaw '),
    ('It\'s not whether you get knocked down it\'s whether you get up. Vince Lombardi'),
    ('Goals are powerful motivators but they can also make you miserable. World-class daily habits are what you need. Maxime Lagacce'),
    ('To give anything less than your best is to sacrifice the gift. Steve Prefontaine'),
    ('If you are not willing to risk the usual you will have to settle for the ordinary. Jim Rohn'),
    ('You\'re never a loser until you quit trying. Mike Ditka'),
    ('Success isn\'t permanent and failure isn\'t fatal. Mike Ditka'),
    ('How much can you know about yourself if you\'ve never been in a fight? Fight Club'),
    ('Don\'t ever let good enough be good enough. Bill Parcells'),
    ('Individuals play the game but teams win championships. Bill Parcells'),
    ('Set your goals high and don\'t stop till you get there. Bo Jackson'),
    ('There will be obstacles. There will be doubters. There will be mistakes. But with hard work there are no limits. Michael Phelps'),
    ('When you want to succeed as bad as you want to breathe then you\'ll be successful. Eric Thomas'),
    ('The devotion of thought to an honest achievement makes the achievement possible. Mary Baker Eddy'),
    ('In the long run we only hit what we aim at. Henry David Thoreau'),
    ('The first man gets the oyster the second man gets the shell. Andrew Carnegie'),
    ('Desire is the starting point of all achievement not a hope not a wish but a keen pulsating desire which transcends everything. Napoleon Hill'),
    ('Today I will do what others won\'t so tomorrow I can do what others can\'t. Jerry Rice '),
    ('The greatest danger we face is the mind going soft. Robert Greene'),
    ('Little minds are tamed and subdued by misfortune: but great minds rise above it. Washington Irving'),
    ('If you see it in your mind you will hold it in your hand. Bob Proctor'),
    ('Continuous improvement is better than delayed perfection. Mark Twain'),
    ('Excellence is an art won by training and habituation. Aristotle '),
    ('If you want something you never had you have to do something you\'ve never done. Thomas Jefferson'),
    ('Make your habits so specific and your dreams so inspiring that motivation will take care of itself. Maxime Lagacce'),
    ('Success isn\'t always about greatness. It\'s about consistency. Consistent hard work gains success. Dwayne Johnson (The Rock)'),
    ('There is only one corner of the universe you can be certain of improving and that\'s your own self. Aldous Huxley'),
    ('Do 40 hard minutes not an hour and a half of nonsense. Jason Statham'),
    ('It\'s not about perfect. It\'s about effort. And when you bring that effort every single day that\'s where transformation happens. That\'s how change occurs. Jillian Michaels'),
    ('People who are unable to motivate themselves must be content with mediocrity no matter how impressive their other talents. Andrew Carnegie'),
    ('It is the mind that makes the body rich. Andrew Carnegie'),
    ('Motivation is what gets you started. Habit is what keeps you going. Jim Rohn '),
    ('Successful people do what unsuccessful people are not willing to do. Don\'t wish it were easier wish you were better. Jim Rohn'),
    ('Patience persistence and perspiration make an unbeatable combination for success. Napoleon Hill'),
    ('Lack of emotion causes lack of progress and lack of motivation. Tony Robbins'),
    ('If you can\'t you must. If you must you can. Tony Robbins'),
    ('If you have no destination you\'ll never get there. Harvey Mackay'),
    ('Effort is only effort when it begins to hurt. Josce Ortega y Gassett'),
    ('No pain no gain. Shut up and train. Unknown'),
    ('Making excuses burns zero calories per hour. Unknown'),
    ('Without self-discipline success is impossible. Period. Unknown'),
    ('One hour from now do you want to be sweaty   or sorry? Unknown'),
    ('Don\'t stop when you\'re tired. Stop when you are done. Unknown'),
    ('You\'re only one workout away from a good mood. Unknown'),
    ('Train insane or remain the same. Unknown'),
    ('It does not matter how slowly you go so long as you do not stop. Confucius'),
    ('Success is measured by your discipline and inner peace. Mike Ditka'),
    ('Look in the mirror that\'s your competition. Eric Thomas'),
    ('If someone tells you you can\'t they\'re showing you their limits not yours. Dwayne Johnson (The Rock) '),
    ('The most certain way to succeed is always to try just one more time. Thomas A. Edison'),
    ('Do what is right not what is easy nor what is popular. Roy T. Bennett'),
    ('Popularity games is what envious kids play. Long term learning games is what smart kids play. Maxime Lagacce'),
    ('Education is the key to unlock the golden door of freedom. George Washington Carver'),
    ('Nothing great ever came that easy. Kresley Cole'),
    ('Without a struggle there can be no progress. Frederick Douglass'),
    ('You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose. Dr. Seuss'),
    ('The more that you read the more things you will know. The more that you learn the more places you\'ll go. Dr. Seuss'),
    ('Anyone who stops learning is old whether at twenty or eighty. Anyone who keeps learning stays young. The greatest thing in life is to keep your mind young. Henry Ford'),
    ('There is nothing noble in being superior to your fellow men. True nobility lies in being superior to your former self. Ernest Hemingway'),
    ('Nothing in life is to be feared it is only to be understood. Now is the time to understand more so that we may fear less. Marie Curie'),
    ('Stop hating yourself for everything you aren\'t and start loving yourself for everything you already are. Unknown'),
    ('People do not decide to become extraordinary. They decide to accomplish extraordinary things. Edmund Hillary '),
    ('Anything is possible when you are inner peace. Master Shifu (Kung Fun Panda)'),
    ('You\'ve gotta let go of that stuff from the past because it just doesn\'t matter! The only thing that matters is what you choose to be now. Po (Kung Fu Panda)'),
    ('Life is a gift and it offers us the privilege opportunity and responsibility to give something back by becoming more. Tony Robbins'),
    ('Successful people ask better questions and as a result they get better answers. Tony Robbins'),
    ('The more you give the more comes back to you. Napoleon Hill'),
    ('I have no special talents. I am only passionately curious. Albert Einstein'),
    ('By failing to prepare you are preparing to fail. Benjamin Franklin '),
    ('There\'s a way to do it better find it. Thomas A. Edison'),
    ('A creative man is motivated by the desire to achieve not by the desire to beat others. Ayn Rand'),
    ('Learn to be happy with the endless try/fail/learn approach. True growth is slow and steady. Maxime Lagacce'),
    ('Nothing ever comes to one that is worth having except as a result of hard work. Booker T. Washington'),
    ('If you shut the door to all errors truth will be shut out. Rabindranath Tagore'),
    ('My goal is not to be better than anyone else but to be better than I used to be. Wayne Dyer'),
    ('Don\'t ask for what the world needs. Ask what makes you come alive and go do it. Brence Brown'),
    ('I am just a child who has never grown up. I still keep asking these\'how\' and\'why\' questions. Occasionally I find an answer. Stephen Hawking'),
    ('Apply yourself. Get all the education you can but then by God do something. Don\'t just stand there make it happen. Lee Iacocca'),
    ('Forget the mistake. Remember the lesson. Unknown'),
    ('Be ready to fail because only then you are ready to succeed. Unknown'),
    ('You were born to be real not perfect. Unknown'),
    ('Making mistakes is better than faking perfections. Unknown'),
    ('Do something wonderful people may imitate it. Albert Schweitzer '),
    ('If you only do what you can do you will never be more than you are now. Master Shifu (Kung Fu Panda)'),
    ('The days you don\'t want to are the days you have to if you want to reach your goal. Jay Shetty'),
    ('Best lesson I have learned in life came from the worst feeling I ever felt in life. Jay Shetty'),
    ('Challenges are what make life interesting and overcoming them is what makes life meaningful. Joshua J. Marine'),
    ('Learning is the only thing the mind never exhausts never fears and never regrets. Leonardo da Vinci'),
    ('Who is wise? He that learns from everyone. Benjamin Franklin'),
    ('The expert at anything was once a beginner. Helen Hayes'),
    ('She believed she could so she did. Unknown '),
    ('Life is tough darling but so are you. Stephanie Bennett-Henry'),
    ('Have no fear of perfection: you\'ll never reach it. Marie Curie'),
    ('Only I can change my life. No one can do it for me. Carol Burnett'),
    ('Perseverance is failing 19 times and succeeding the 20th. Julie Andrews'),
    ('Our deepest fear is not that we are inadequate. Our deepest fear is that we are powerful beyond measure. Marianne Williamson'),
    ('I attribute my success to this: I never gave or took any excuse. Florence Nightingale'),
    ('We must have perseverance and above all confidence in ourselves. We must believe that we are gifted for something and that this thing must be attained. Marie Curie'),
    ('She remembered who she was and the game changed. Lalah Delia'),
    ('You have the power to change the course of your life with each thought habit and action. Make it count. Lalah Delia'),
    ('Self-care is how you take your power back. Lalah Delia'),
    ('Choose people who choose you. Jay Shetty'),
    ('A bad day for your ego is a great day for your soul. Jillian Michaels'),
    ('I never dreamed about success. I worked for it. Estee Lauder'),
    ('Everything you\'ve ever wanted is on the other side of fear. George Addair '),
    ('The soul that is within me no man can degrade. Frederick Douglass'),
    ('The world turns aside to let any man pass who knows where he is going. Epictetus'),
    ('He who wishes to be rich in a day will be hanged in a year. Leonardo da Vinci'),
    ('Deep down you know what you want. Deep down you have what it takes. Maxime Lagacce'),
    ('If you had one shot or one opportunity to seize everything you ever wanted in one moment. Would you capture it or just let it slip? Eminem'),
    ('The man who acquires the ability to take full possession of his own mind may take possession of anything else to which he is justly entitled. Andrew Carnegie'),
    ('Either write something worth reading or do something worth writing. Benjamin Franklin'),
    ('Start by doing what\'s necessary: then do what\'s possible: and suddenly you are doing the impossible. Francis of Assisi'),
    ('I learned that courage was not the absence of fear but the triumph over it. The brave man is not he who does not feel afraid but he who conquers that fear. Nelson Mandela'),
    ('The greatest danger for most of us is not that our aim is too high and we miss it but that it is too low and we reach it. Michaelangelo'),
    ('Cherish your visions and your dreams as they are the children of your soul the blueprints of your ultimate achievements. Napoleon Hill'),
    ('I am not a product of my circumstances. I am a product of my decisions. Stephen Covey'),
    ('Without ambition one starts nothing. Without work one finishes nothing. The prize will not be sent to you. You have to win it. Ralph Waldo Emerson'),
    ('Whatever you hold in your mind on a consistent basis is exactly what you will experience in your life. Tony Robbins'),
    ('The man who moves a mountain begins by carrying away small stones. Confucius'),
    ('Be brave to stand for what you believe in even if you stand alone. Roy T. Bennett'),
    ('We aim above the mark to hit the mark. Ralph Waldo Emerson '),
    ('Definiteness of purpose is the starting point of all achievement. W. Clement Stone'),
    ('Problems are not stop signs they are guidelines. Robert H. Schuller'),
    ('I was not the most talented but I was the one who worked the hardest. It made all the difference. Maxime Lagacce'),
    ('You will never be able to hit a target that you cannot see. Robin Sharma'),
    ('A lot of people will just stop because they\'re dead tired. You gotta do that extra one. That\'s when you improve. Usain Bolt'),
    ('No matter how far you think you are ahead of me I\'m going to catch you. That\'s my mentality that I go out there with. Usain Bolt'),
    ('You don\'t get any medal for trying something you get medals for results. Bill Parcells'),
    ('Never let the world define you as less than great. Bill Parcells'),
    ('The worst thing I can be is the same as everybody else. I hate that. Arnold Schwarzenegger'),
    ('I didn\'t want to just be a body building champion. I wanted to be the best body builder of all time. Arnold Schwarzenegger'),
    ('Stop being afraid of what could go wrong and think of what could go right. Unknown'),
    ('When everything seems to be going against you remember that the airplane takes off against the wind not with it. Henry Ford'),
    ('I believe that the true road to preeminent success in any line is to make yourself master of that line. Andrew Carnegie'),
    ('Most of the important things in the world have been accomplished by people who have kept on trying when there seemed to be no hope at all. Dale Carnegie'),
    ('You\'ll never get ahead of anyone as long as you try to get even with him. Lou Holtz '),
    ('Every adversity every failure and every heartache carries with it the seed of an equivalent or greater benefit. Napoleon Hill'),
    ('You cannot swim for new horizons until you have courage to lose sight of the shore. William Faulkner'),
    ('The real secret to success is enthusiasm. Walter Chrysler'),
    ('Never think there is anything impossible for the soul. Swami Vivekananda'),
    ('One way to keep momentum going is to have constantly greater goals. Michael Korda'),
    ('Make the most of yourself for that is all there is of you. Ralph Waldo Emerson'),
    ('It\'s what you practice in private that you will be rewarded for in public. Tony Robbins'),
    ('Without ambition one starts nothing. Without work one finishes nothing. The prize will not be sent to you. You have to win it. Ralph Waldo Emerson ');
